### ISSUE TITLE
[BUG] Cannot be compiled

### ISSUE THREAD

**Issue by xoredamn** [LameuleFR/altv-csharp-streamer#1]
**Describe the bug**
Cannot be compiled when added to a valid C# project

**To Reproduce**
Remove all additionally installed library's like **'TheSantos.Models.Entities.Network'** and **'org.bouncycastle.tls.crypto'**

**Expected behavior**
Compiling will fail, because the library's are not installed

**Additional context**
Remove the package 'TheSantos.Models.Entities.Network'  from 'DoorManager.cs' in line 7
Remove the package 'org.bouncycastle.tls.crypto' from 'BlipManager.cs' in line 6

**Comment by LameuleFR** [comment]
Thank you for your bug report even if it is a minor oversight that can be easily corrected

It's fixed with the latest commit !
